# $Id$

SUBDIR= 	studyguide
SUBDIR+= 	../labs/mobusability/
SUBDIR+= 	../seminars/mobusability/
SUBDIR+= 	../seminars/design/
SUBDIR+= 	../projects/app/

INCLUDE_MIUNTEX=../miuntex
INCLUDE_MAKEFILES=../makefiles
include ${INCLUDE_MAKEFILES}/subdir.mk
