# $Id$

SUBDIR=		studyguide
SUBDIR+= 	../labs/usability/
SUBDIR+= 	../seminars/design/
SUBDIR+= 	../projects/interactivesys/

INCLUDE_MIUNTEX=../miuntex
INCLUDE_MAKEFILES=../makefiles
include ${INCLUDE_MAKEFILES}/subdir.mk
